# Generated by Django 5.0.7 on 2024-08-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_variant_images',
        ),
    ]
