# Generated by Django 5.0.7 on 2024-08-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_image_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Variant',
            new_name='ProductVariant',
        ),
    ]
