# Generated by Django 5.0.7 on 2024-08-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productvariant_colour_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
